-- MySQL Script generated by MySQL Workbench
-- Tue May  4 01:56:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema umbrella
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `umbrella` ;

-- -----------------------------------------------------
-- Schema umbrella
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `umbrella` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `umbrella` ;

-- -----------------------------------------------------
-- Table `umbrella`.`clearance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umbrella`.`clearance` ;

CREATE TABLE IF NOT EXISTS `umbrella`.`clearance` (
  `clearance_id` INT NOT NULL AUTO_INCREMENT,
  `clearance_description` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`clearance_id`)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `umbrella`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umbrella`.`department` ;

CREATE TABLE IF NOT EXISTS `umbrella`.`department` (
  `dept_id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NOT NULL,
  `dept_abb` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dept_id`),
  UNIQUE INDEX `dept_name_UNIQUE` (`dept_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `umbrella`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umbrella`.`employee` ;

CREATE TABLE IF NOT EXISTS `umbrella`.`employee` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(75) NOT NULL,
  `middle_name` VARCHAR(75) NULL,
  `last_name` VARCHAR(75) NOT NULL,
  `birth_date` DATE NOT NULL,
  `job` VARCHAR(30) NOT NULL,
  `department_code` INT NOT NULL,
  `hire_date` DATETIME NOT NULL,
  `clearance_level` INT NOT NULL,
  `address` VARCHAR(75) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `salary_code` INT NOT NULL,
  PRIMARY KEY (`emp_id`),
  INDEX `dept_code_index` (`department_code` ASC) VISIBLE,
  INDEX `clearance_code_index` (`clearance_level` ASC) VISIBLE,
  INDEX `salary_code_index` (`salary_code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `umbrella`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `umbrella`.`salary` ;

CREATE TABLE IF NOT EXISTS `umbrella`.`salary` (
  `salary_id` INT NOT NULL AUTO_INCREMENT,
  `salary_desc` VARCHAR(45) NOT NULL,
  `salary_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`salary_id`)
  )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
